# Elastic Workflow: Create GitHub Issue
# Copy this into Kibana → Management → Workflows

name: create_github_issue
description: Create a GitHub issue for incident tracking

inputs:
  - name: title
    type: string
    description: Issue title
  - name: body
    type: string
    description: Issue body with incident details

triggers:
  - type: manual

consts:
  # Replace with your values
  github_token: "ghp_YOUR_TOKEN_HERE"
  repo_owner: "YOUR_GITHUB_USERNAME"
  repo_name: "YOUR_REPO_NAME"

steps:
  - name: create_issue
    type: http
    with:
      method: POST
      url: "https://api.github.com/repos/{{ consts.repo_owner }}/{{ consts.repo_name }}/issues"
      headers:
        Authorization: "Bearer {{ consts.github_token }}"
        Accept: "application/vnd.github+json"
        Content-Type: "application/json"
        X-GitHub-Api-Version: "2022-11-28"
      body:
        title: "{{ inputs.title }}"
        body: "{{ inputs.body }}"
        labels:
          - "incident"
          - "auto-generated"
